version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "fvdm"
    commit-message:
      prefix: "Chore(github)"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "fvdm"
    commit-message:
      prefix: "Chore(deps)"
      prefix-development: "Chore(devdeps)"
    allow:
      - dependency-type: "production"

