name: "Node.js"

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ develop ]
  schedule:
    - cron: '42 18 * * 6'

jobs:
  lts_versions:
    name: "Get versions"
    runs-on: ubuntu-latest
    steps:
      - id: set-matrix
        run: echo "matrix=$(curl -s https://raw.githubusercontent.com/fvdm/nodejs-versions/main/lts-current.json)" >> $GITHUB_OUTPUT
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

  build:
    name: "Node"
    needs: lts_versions
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ${{ fromJson(needs.lts_versions.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4
      - name: Test on Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm test
        env:
          GEOIP2WS_USERID: ${{ secrets.GEOIP2WS_USERID }}
          GEOIP2WS_LICENSE: ${{ secrets.GEOIP2WS_LICENSE }}
          GEOIP2WS_SERVICE: ${{ secrets.GEOIP2WS_SERVICE }}
          GEOIP2WS_ENDPOINT: ${{ secrets.GEOIP2WS_ENDPOINT }}
          GEOIP2WS_TIMEOUT: ${{ secrets.GEOIP2WS_TIMEOUT }}
          DOTEST_NOCOV: ${{ secrets.DOTEST_NOCOV }}
          DOTEST_MINCOV: ${{ secrets.DOTEST_MINCOV }}
          DOTEST_COVFUNCTIONS: 100
      - name: Coveralls Parallel
        uses: coverallsapp/github-action@master
        if: always()
        continue-on-error: true
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          flag-name: node-${{ matrix.node-version }}
          parallel: true

  good_build:
    name: "Good build"
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: echo "Build was sucessfull"

  finish:
    name: "Upload coverage"
    needs: build
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@master
        continue-on-error: true
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
