name: Build
on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['10', '12', '14', '16']
    name: Node ${{ matrix.node }}
    steps:
    - uses: actions/checkout@v2
    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node }}
    - run: git fetch --prune --unshallow
    - run: npm install
    - run: npm test
    - run: npm audit
